language: python
python:
    - "3.6"

services:
    - docker

before_script: pip install docker-compose

script:
    - docker-compose run notifi sh -c "python manage.py test && flake8"

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker tag notifi-2021_notifi jacobvinoo/notifi-2021_notifi
    - docker push jacobvinoo/notifi-2021_notifi:latest

deploy:
    provider: elasticbeanstalk
    region: us-east-1
    app: notifi
    env: Notifi-env-1
    bucket_name: elasticbeanstalk-us-east-1-744042447806
    bucket_path: notifi
    on: 
        repo: jacobvinoo/notifi-2021
        branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY