version: "3.8"

services:
    notifi:
        build:
            context: .
        ports:
         - "8000:8000"
        volumes:
         - ./source:/source
        command: >
         sh -c "python manage.py runserver 0.0.0.0:8000"