version: '3.8'

services:
    notifi:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - ./source:/source
            - static_data:/vol/web
        command: >
            sh -c "python manage.py wait_for_db && 
                python manage.py migrate &&
                python manage.py runserver 0.0.0.0:8000"
        environment:
            - DEBUG=1
            - DB_HOST=db
            - DB_NAME=notifi
            - DB_USER=postgres
            - DB_PASS=supersecretpassword

            - SECRET_KEY=samplesecret123
            - ALLOWED_HOSTS=127.0.0.1,localhost
        depends_on:
            - db

    db:
        image: postgres:10-alpine
        environment:
            - POSTGRES_DB=notifi
            - POSTGRES_USER=postgres 
            - POSTGRES_PASSWORD=supersecretpassword 

    proxy:
        build:
            context: ./proxy
        volumes:
            - static_data:/vol/static
        ports:
            - "8080:8080"
        depends_on:
            - notifi

volumes:
    static_data: