# Generated by Django 3.1.3 on 2020-12-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_auto_20201213_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='service_id',
            field=models.CharField(default='A2535', max_length=50),
            preserve_default=False,
        ),
    ]
