# Generated by Django 3.1.3 on 2021-01-02 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0005_auto_20210101_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='orgin_company',
            new_name='origin_company',
        ),
    ]
