# Generated by Django 3.1.3 on 2021-01-03 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0007_auto_20210102_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='admin_person',
        ),
    ]
