# Generated by Django 3.1.3 on 2021-01-05 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0010_auto_20210105_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='service_id',
            new_name='service',
        ),
    ]
