# Generated by Django 3.1.3 on 2021-01-05 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0011_auto_20210105_0111'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='date_of_outage',
            new_name='window_end_date',
        ),
        migrations.AddField(
            model_name='notification',
            name='window_start_date',
            field=models.DateField(default=datetime.date(2020, 12, 23)),
            preserve_default=False,
        ),
    ]
