# Generated by Django 3.1.3 on 2021-01-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0013_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='destination_company',
        ),
        migrations.AddField(
            model_name='notification',
            name='destination_company',
            field=models.ManyToManyField(related_name='destination', to='notify.Company'),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='service',
        ),
        migrations.AddField(
            model_name='notification',
            name='service',
            field=models.ManyToManyField(to='notify.Service'),
        ),
    ]
